#!/bin/sh

# clobber everything
rm -rf output

# recursive copy the theme
cp -r templates/oldschool output

# pump out of module to index.html
node index.js

# open in browser
open output/default/index.html
